export const SELECTED_SPENDING_LIMIT = 'SELECTED_SPENDING_LIMIT';

export const USER_DATA = {
  FETCH_USER_DATA: 'FETCH_USER_DATA',
  USER_DATA_START: 'USER_DATA_START',
  USER_DATA_SUCCESS: 'USER_DATA_SUCCESS',
  USER_DATA_FAILED: 'USER_DATA_FAILED',
  USER_DATA_END: 'USER_DATA_END',
};
